### ISSUE TITLE
Update liveblog nav and footer

### ISSUE THREAD

**Issue by audreycarlsen** [nprapps/elections20-interactive#113]
Should top nav match results nav?

![image](https://user-images.githubusercontent.com/5515746/97605685-4faee800-19e5-11eb-9108-ca8879c4f68a.png)
versus
![image](https://user-images.githubusercontent.com/5515746/97605719-59d0e680-19e5-11eb-8434-ecdcb05c7138.png)

Also, links to results in footer should go to general election results not primaries.

**Comment by thomaswilburn** [comment]
I've updated the footer, and will update the header as well this afternoon.

**Comment by alykat** [comment]
should we choreograph this a little? https://github.com/nprapps/liveblog-standalone/issues/73

**Comment by thomaswilburn** [comment]
Mm, good point. I'll add a config flag that suppresses that stuff until results are live.

**Comment by audreycarlsen** [comment]
Should liveblog nav on mobile look more like results pages? So that results links are still surfacing.

![image](https://user-images.githubusercontent.com/5515746/97783776-4605bb80-1b70-11eb-814d-98deea7d74df.png)
versus
![image](https://user-images.githubusercontent.com/5515746/97783788-5453d780-1b70-11eb-84d6-50befcf53526.png)

**Comment by alykat** [comment]
That makes sense to me — we'll just need to make sure it doesn't go up until later on Monday.

**Comment by thomaswilburn** [comment]
These are updated to match now.
