### ISSUE TITLE
Updates to BOP widget

### ISSUE THREAD

**Issue by alykat** [nprapps/elections20-interactive#119]
- [x] Per Wash Desk: When we have 3 in a row on desktop (like on the top of the liveblog), put president in the middle
- [x] For House/Senate, add net gain
- [x] More explicitly call out "See full results" at the end of the chatter line (218 needed for majority | See full results >)
- [x] Links should be set to target _top

**Comment by audreycarlsen** [comment]
@alykat Do we care that these wrap inconsistently? Solution might be to always have them on separate lines.
![image](https://user-images.githubusercontent.com/5515746/97646417-fd41eb80-1a25-11eb-9cf5-d423c3b71e60.png)
