### ISSUE TITLE
Generate "other" candidates

### ISSUE THREAD

**Issue by thomaswilburn** [nprapps/elections20-interactive#12]
Probably makes sense to do this at the data level. See also: https://github.com/nprapps/elections18-general/blob/master/fabfile/render.py#L608

**Comment by audreycarlsen** [comment]
LA Senate race results (using AP test data on 10/6) not coming through with leading candidate first:

{
    "test": true,
    "id": "20157",
    "office": "S",
    "eevp": 97,
    "type": "General",
    "description": "Class II",
    "level": "state",
    "state": "LA",
    "updated": 1602016529443,
    "reporting": 3934,
    "precincts": 3934,
    "previousParty": "GOP",
    "candidates": [
      {
        "first": "Bill",
        "last": "Cassidy",
        "party": "GOP",
        "id": "59656",
        "votes": 511036,
        "avotes": 3355,
        "winner": "R",
        "incumbent": true,
        "percent": 0.2473
      },
      {
        "first": "Derrick",
        "last": "Edwards",
        "party": "Dem",
        "id": "65597",
        "votes": 255060,
        "avotes": 144,
        "winner": "R",
        "percent": 0.1234
      },
      {
        "first": "",
        "last": "Other",
        "party": "Other",
        "id": "other-20157",
        "votes": 1300106,
        "avotes": 4442,
        "electoral": 0,
        "percent": 0.6292
      }
    ]
  }
