### ISSUE TITLE
3% might be too low a threshold for showing results in a tooltip

### ISSUE THREAD

**Issue by alykat** [nprapps/elections20-interactive#124]
Applies to presidential bubbles + maps

(If we do change threshold, make sure to also update in source line on state pages.)

![image](https://user-images.githubusercontent.com/491318/97632660-3455d400-1a09-11eb-8003-cde91f480cad.png)

**Comment by audreycarlsen** [comment]
And on results tables: 
![image](https://user-images.githubusercontent.com/5515746/97639098-4a1cc680-1a14-11eb-90f4-a19147c3fa76.png)
