### ISSUE TITLE
Update references to the electoral/battleground map to point to the 10/30 story

### ISSUE THREAD

**Issue by alykat** [nprapps/elections20-interactive#127]
I think this appears in the results + liveblog footer and maybe in the footnote for the presidential big board

**Comment by alykat** [comment]
Story is published now: https://www.npr.org/2020/10/30/929077049/final-npr-electoral-map-biden-has-the-edge-but-trump-retains-narrow-path

**Comment by thomaswilburn** [comment]
Done in the sheet and nprapps/liveblog-standalone@6edf2f4
