### ISSUE TITLE
Safari fixes

### ISSUE THREAD

**Issue by audreycarlsen** [nprapps/elections20-interactive#140]
![IMG_6606](https://user-images.githubusercontent.com/5515746/97783651-9fb9b600-1b6f-11eb-8d57-29a8375eb1f9.PNG)
![IMG_6605](https://user-images.githubusercontent.com/5515746/97783653-a1837980-1b6f-11eb-936c-3357b873565a.PNG)

**Comment by thomaswilburn** [comment]
LOG OFF
