### ISSUE TITLE
"Winner" coloring issues on maps/bubbles

### ISSUE THREAD

**Issue by audreycarlsen** [nprapps/elections20-interactive#141]
On maps and bubbles: Tennessee "winnerParty" attribute is coming through as "Dem" even though Trump marked as winner.

![image](https://user-images.githubusercontent.com/5515746/97814952-dcada780-1c58-11eb-9d99-eb7bf0afa913.png)

From Arnie: Illinois has been called for Biden, but because the vote count at the moment has Trump ahead, it's filled in red.

![image](https://user-images.githubusercontent.com/5515746/97814940-c4d62380-1c58-11eb-8abe-6caf6b856610.png)

**Comment by thomaswilburn** [comment]
The Illinois issue is fixed--I'll take a look at what's going on with Tennessee when I can. Did you grab a capture of the API response?
