### ISSUE TITLE
Embeds: Links should target _top or _blank

### ISSUE THREAD

**Issue by alykat** [nprapps/elections20-interactive#143]
Use case: User goes to one of the [boards](https://www.npr.org/2020/11/03/928083901/2020-gubernatorial-election-live-results), clicks on a state, and gets stuck with no navigation to other parts of the experience. I think the ideal would be that if the user clicks on a state, they're busted out of the embed experience.

Exception: Clicks to links within state pages (nav, detailed results, etc.) should probably stay within the iframe, for stations.

**Comment by thomaswilburn** [comment]
The back button works, if that counts for anything.

**Comment by alykat** [comment]
Yeah, but that's not as intuitive on mobile. The [Seamus version of the presidential board](https://www.npr.org/2020/11/03/928083390/2020-presidential-election-results-live) is ranked 5th on the site right now.
