### ISSUE TITLE
A11y audit

### ISSUE THREAD

**Issue by thomaswilburn** [nprapps/elections20-interactive#22]
Test for navigation, focus assignment (should happen at the router level), Lighthouse audit, and mobile navigation

**Comment by audreycarlsen** [comment]
Also check everything for colorblindness

**Comment by thomaswilburn** [comment]
Screen reader tests look good in VO and NVDA. Lighthouse puts us in the high 90's for perf and a11y on most views (president is a bit worse, due to the visualization hitting the CPU so hard). I think we're solid.
