### ISSUE TITLE
Pull final race predictions from Cook/Domenico on Fri Oct. 30

### ISSUE THREAD

**Issue by alykat** [nprapps/elections20-interactive#25]
- [x] State ratings are updated
- [x] Senate ratings are updated
- [x] House ratings are updated
- [x] Gov. ratings are updated
- [x] Electoral map link is updated (footer, liveblog, presidential board source line)

**Comment by thomaswilburn** [comment]
- [x] State ratings are updated
- [x] Senate ratings are updated
- [ ] House ratings are updated
- [ ] Gov. ratings are updated
