### ISSUE TITLE
Various results widgets

### ISSUE THREAD

**Issue by thomaswilburn** [nprapps/elections20-interactive#30]
Current plan: Presidential BOP bar and board of state calls, plus links to the main page. They'll also use a liveblog widget--make sure that's updated on the election liveblog branch.

Overview of results widgets: https://docs.google.com/document/d/1-acdjrYPsgD72hCodU4Y-NnFFFlbhcHAjuE4l79r3Eg/edit#

- [ ] Homepage embed
- [x] Homepage BOP embed (Audrey)
- [x] Sidebar BOP embed for stories/stations (Audrey)
- [ ] Liveblog header embed

**Comment by audreycarlsen** [comment]
Various Election 2020 Results Widgets: https://docs.google.com/document/d/1-acdjrYPsgD72hCodU4Y-NnFFFlbhcHAjuE4l79r3Eg/edit#heading=h.g9pdv85k8vb
