### ISSUE TITLE
Liveblog: Results embed for top header

### ISSUE THREAD

**Issue by alykat** [nprapps/elections20-interactive#73]
Need to confirm reqs from Wash Desk. In theory, this would include electoral college + BOP bars ([what we did in 2016](https://www.npr.org/2016/11/08/500427835/live-blog-election-night-2016), tho this time not grouped into GCU).

Wash Desk has also previously expressed interest in a "sticky bar" fixed to the top to keep those top-level numbers visible as users scroll down.

**Comment by audreycarlsen** [comment]
More info on widgets: https://docs.google.com/document/d/1-acdjrYPsgD72hCodU4Y-NnFFFlbhcHAjuE4l79r3Eg/edit#

**Comment by audreycarlsen** [comment]
Light and dark themes
