### ISSUE TITLE
Bubble chart: Tabbing back to bubble chart after being away, sometimes only a giant "MD" bubble is visible

### ISSUE THREAD

**Issue by alykat** [nprapps/elections20-interactive#76]
It rights itself on resize or after clicking to another tab and back.

![image](https://user-images.githubusercontent.com/491318/97199112-0319a180-1786-11eb-89b1-8af656b2a778.png)

**Comment by thomaswilburn** [comment]
This should be fixed in the latest code, it had to do with the way that tabs are hidden and the order that the intersection observer updates.
