### ISSUE TITLE
Page jumps when you switch tabs

### ISSUE THREAD

**Issue by audreycarlsen** [nprapps/elections20-interactive#82]
The page jumps down to the bubbles/maps area when you click on the tabs, which is disorienting. Should keep tabs on page view.

**Comment by thomaswilburn** [comment]
I think this is related to sending focus, which we do need to so. I'll see if I can reset page position after the update.

**Comment by thomaswilburn** [comment]
Even better, there's an option to prevent scrolling: https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus
